Align the declarative shadowroot with specs
github/catalyst pull request #136
Opened 2021-04-14 18:31 UTC by dgrammatiko

This PR is using `shadowroot` attribute instead of `data-shadowroot` and should be aligned with the specs (Chrome 90 already shipped this)

Ref: https://web.dev/declarative-shadow-dom/

It might worth changing the logic a bit further here, eg template needs to be the first child element and should be only one template per web-component (if I'm reading correctly the specs)

2021-04-15 08:55 UTC, koddsson commented
I'm worried that this will clash with the declarative shadow DOM spec. What happens when you run this branch in a browser that has the declarative Shadow DOM enabled?

2021-04-15 10:11 UTC, keithamus requested changes
This is a great PR and super well motivated! We definitely want to align with the declarative ShadowDOM spec!

Using `data-shadowroot` was an intentional choice to avoid colliding with `shadowroot`. Think of it like a polyfill until we could use `shadowroot` in earnest. 

When it comes to browsers shipping `shadowroot` in large enough %s we should move Catalyst over to it. I think the way we'll do that is delete all code involving `data-shadowroot`, and update the docs to point to the spec. 

The PR as stands will conflict with native behaviours, so it's not something we want to merge as it stands. @dgrammatiko if you'd like to update this PR to delete the files we can keep it around for when we want to cut a major release, for when browsers are ready. Otherwise we can close this out for now and reopen when the time comes.

2021-04-15 11:56 UTC, dgrammatiko commented
> I'm worried that this will clash with the declarative shadow DOM spec

That's correct but it can be done in a more progressive way


> When it comes to browsers shipping shadowroot in large enough %s we should move Catalyst over to it.

So, my idea was that since chromium-based browsers that account for more than 60% will soon support this and thus would be nice to align the code here with the platform provided functionality. Obviously, my code was mainly sudo-code just to check if this was something that would be something worth of exploring. That said I think that it can be done in such a way that B/C is not broken and also the move (mainly the docs part) could move to the spec complaint `[shadowroot]`. I already pushed some changes that should be safe for both cases (old or new attribute), but also don't mind if this is closed and handled differently at some point.

2021-04-16 09:25 UTC, keithamus reviewed
Thanks for responding @dgrammatiko and starting this dialog.

It looks like we're on the way to implementing a polyfill, which to me is a sign we should alter course. Absolutely nothing wrong with polyfills, in fact we want to encourage them! I think Catalyst itself should not polyfill anything (perhaps, in part, it was a mistake to ship `data-shadowroot` in the first place) and instead we should encourage independent polyfills.

I think I'd like us to investigate how feasible an independent `shadowroot` polyfill is, and if there is one we can recommend, we should change our docs to recommend it. If we can't find a suitable independent polyfill we can then look to what we can do with this PR. Sound good?

2021-04-19 11:27 UTC, dgrammatiko commented
> I think I'd like us to investigate how feasible an independent shadowroot polyfill is, and if there is one we can recommend, we should change our docs to recommend it

That's excellent. I think I can close this one here

2021-04-19 11:27 UTC, closed without merging